language: node_js
node_js:
  - "6"

cache:
  directories:
    - project/node_modules
    - $HOME/.cache/yarn

before_install:
  - cd project

install:
  - npm install

script:
  - npm run test:cover

after_success:
  - npm run make-reporter
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - cat ../README.md > README.md
  - npm run build:prod

deploy:
  provider: npm
  email: tonypythoneer@gmail.com
  api_key:
    secure: tFExacXse0asTZB8ba9CZje+zXaIZcm7UBtf982OSRjcrZlKHIMBHtduatcgNe9l1ndSDvghqzqDe53ffHt4u+e27gePsTLPukbRC7A/jvY4+vReTSZmNl/0GeUxZvHWpTQMqGZQaNWA6GFzmIVDJ9MBNr8Un1n+FUWJ8cJrrFCqzoloJnyjwXt5USC4OhJyNvfB6daCkee81MtSRP/OauyAPlWfXlyAKFjpFaL1PhHetx59Zn1NmtnmumaKGGYQAx3tbfuFW/5+pG/dP0ZfthOuk5bV+y0P7cgjq2XfIfxazBb6DEQmdQNTkqh/w3AdmijQnGRK7QZoU8QKDOJ4haKFZTBYgYaJxMSnsb/X7/ADh73ctq3DregpOPTSBObxc9DFJGQ2uWE/GiWuYYn97WcEQerdHhHNxU94rtAO3yp6juXTeYXLA1eTX7lpClHCzP1XITsILFjgmT7d0adn8TihVoXf7yquzNvtW3j4FFaosYQI+z6uTW/gKNR0Xz4MYMSjyDA5ay+gPJhbsByr0p+h4iK0cwSbp+Gaggk3SGm1vabZFGoCqACdypDpWlEX+3wAc7DN/i3cPRei8pc6yG9cs4RRXD+v+n2icql55ps/2jKxUkAavJSREh3UIt/ZtiherNtGP02zKKDye9eJHt87lWJBjcLFxicHC1y9X3I=
  skip_cleanup: true
  on:
    branch: master
